### ISSUE TITLE
可否增加对不同用户的端口限制？Can the port restrictions for different users be increased?

### ISSUE THREAD

**Issue by cr-zhichen** [gofrp/fp-multiuser#12]

**Comment by fatedier** [comment]
这个项目主要起一个示例的作用，不会继续增加功能。

**Comment by cr-zhichen** [comment]
好的 那我fork下代码看看如何增加 顺便问下这个项目是否接受新功能的PR？


________________________________

**Comment by fatedier** [comment]
你可以创建自己的项目，维护自己的插件。

这个项目尽量不做变更。

**Comment by cr-zhichen** [comment]
好的 谢谢


________________________________

**Comment by yhl452493373** [comment]
我搞了一个

https://github.com/yhl452493373/frps-multiuser

**Comment by yunbookf** [comment]
不介意 node 环境的话，可以试试这个
https://github.com/maiyun/fp-multi
除了可以限定端口范围，也可以限定 name、type。
