### ISSUE TITLE
fp-multiuser是否还会兼容更新新版本的frp

### ISSUE THREAD

**Issue by wiseforever** [gofrp/fp-multiuser#22]
frp后续新版本已经采用toml文件作为配置文件，fp-multiuser还会做后续的升级吗，我在frpv.60.0版本中运行不了此插件的运行模式

**Comment by fatedier** [comment]
https://github.com/gofrp/fp-multiuser?tab=readme-ov-file#usage

**Comment by wiseforever** [comment]
> https://github.com/gofrp/fp-multiuser?tab=readme-ov-file#usage

## fp-multiuser 最高支持 frp 的哪个版本？

我测试frpv.60.0。
frps.toml：
```
[plugin.multiuser]
addr = 127.0.0.1:7200
path = /handler
```


frpc.toml:
```
user = "user1"
metadatas.token = "123"
```


fp-multiuser使用的v0.0.2。frp_v60.0的frps与frpc均启动不起来。我目前是通过降级到frp_v0.34.1版本。
frp_v60.0在不使用fp-multiuser插件的时候，使用token是能够正常启动的，不会因为我个人的配置问题发生错误。还望解答，谢谢。

**Comment by wiseforever** [comment]
> > https://github.com/gofrp/fp-multiuser?tab=readme-ov-file#usage
> 
> ## fp-multiuser 最高支持 frp 的哪个版本？
> 我测试frpv.60.0。 frps.toml：
> 
> ```
> [plugin.multiuser]
> addr = 127.0.0.1:7200
> path = /handler
> ```
> 
> frpc.toml:
> 
> ```
> user = "user1"
> metadatas.token = "123"
> ```
> 
> fp-multiuser使用的v0.0.2。frp_v60.0的frps与frpc均启动不起来。我目前是通过降级到frp_v0.34.1版本。

**Comment by Relief156** [comment]
> > https://github.com/gofrp/fp-multiuser?tab=readme-ov-file#usage
> 
> ## fp-multiuser 最高支持 frp 的哪个版本？
> 我测试frpv.60.0。 frps.toml：
> 
> ```
> [plugin.multiuser]
> addr = 127.0.0.1:7200
> path = /handler
> ```
> 
> frpc.toml:
> 
> ```
> user = "user1"
> metadatas.token = "123"
> ```
> 
> fp-multiuser使用的v0.0.2。frp_v60.0的frps与frpc均启动不起来。我目前是通过降级到frp_v0.34.1版本。 frp_v60.0在不使用fp-multiuser插件的时候，使用token是能够正常启动的，不会因为我个人的配置问题发生错误。还望解答，谢谢。

我一直在用这是支持的 v60.0都是支持的  frpc 可以使用 frp-desktop 他适配了多用插件 在frps中你任然需要 填写
bindAddr = "0.0.0.0"
bindPort = 7000
[[httpPlugins]]
addr = "127.0.0.1:7200"
path = "/handler"
ops = ["Login"]

这样就可以启动了

**Comment by wiseforever** [comment]
> frp-desktop

但是我需要纯命令行的，我不用desktop版本。我一直没空琢磨
