### ISSUE TITLE
能不能增加 --config 参数

### ISSUE THREAD

**Issue by deadlineOvO** [gofrp/fp-multiuser#3]
是的，就像标题一样
至于为什么我会有这个想法
现有的 -l 与 -f 确实很简单，但是我想为它创建一个 systemd 的服务模板时就有一点蹩脚了

下面是可能的配置文件原型

[listen]
addr=127.0.0.1
port=7200
[users]
u1=pass1
u2=pass2

**Comment by fatedier** [comment]
没有太明白，区别在于哪？

**Comment by deadlineOvO** [comment]
> 没有太明白，区别在于哪？

在配置 systemd 的服务模板时，模板只能加一个自定参数
于是启动命令在不用设置变量时在模板里只能以这两个样子出现：
fp-multiuser -l 127.0.0.1:%i -f /path/to/file
fp-multiuser -l 127.0.0.1:7500 -f %i

如果要使用变量去解决另一个参数的话，需要按照发行版的配置另外放置一个参数存放的文件

**Comment by fatedier** [comment]
所以和增加 `--config` 参数有什么关联？

感觉如果 systemd 不能很好的支持，说明不太推荐这种使用方式。

如果像 frp 目前一样支持配置文件模版渲染，是不是可以解决你这个问题？启动进程时指定环境变量。

**Comment by deadlineOvO** [comment]
> 所以和增加 `--config` 参数有什么关联？

希望有 --config 参数把 -l 与 -f 合并在一个文件里

> 感觉如果 systemd 不能很好的支持，说明不太推荐这种使用方式。
> 
> 如果像 frp 目前一样支持配置文件模版渲染，是不是可以解决你这个问题？启动进程时指定环境变量。

在何处指定环境变量？可以举一个例子吗？

**Comment by fatedier** [comment]
哦，我忘记了这个工具由于参数太少，所以并没有支持配置文件。这样的工具使用配置文件感觉有点多此一举。

有没有其他办法能够解决这一类问题？指望每一个应用都能支持好像也不太现实，不是一个优雅的通用解决方案。

**Comment by fatedier** [comment]
我想到一个方案，通过 shell 脚本去启动？在脚本中使用不同的配置。

**Comment by deadlineOvO** [comment]
> 我想到一个方案，通过 shell 脚本去启动？在脚本中使用不同的配置。

脚本解析配置文件然后启动 fp-multiuser 吗？

**Comment by fatedier** [comment]
startA.sh

```bash
fp-multiuser -l 127.0.0.1:7500 -f ./token1
```

startB.sh

```bash
fp-multiuser -l 127.0.0.1:7600 -f ./token2
```

systemd config

```
sh %i
```

`%i` 是脚本路径。

**Comment by deadlineOvO** [comment]
> startA.sh
> 
> ```shell
> fp-multiuser -l 127.0.0.1:7500 -f ./token1
> ```
> 
> startB.sh
> 
> ```shell
> fp-multiuser -l 127.0.0.1:7600 -f ./token2
> ```
> 
> systemd config
> 
> ```
> sh %i
> ```
> 
> `%i` 是脚本路径。

那这样的话就像是我之前说的情况了

systemd config snippet
```
EnvironmentFile=-/etc/fp-multiuser-listen/%i
ExecStart=fp-multiuser -l $ADDR:PORT -f %i
```

绑定地址与端口都需要在另一个文件完成

**Comment by fatedier** [comment]
你想要通过 `--config` 指定配置文件和使用不同 shell 脚本来启动有什么区别吗？

**Comment by deadlineOvO** [comment]
> 你想要通过 `--config` 指定配置文件和使用不同 shell 脚本来启动有什么区别吗？

一个是 fp-multiuser 通过一个文件解析两个参数，另一个通过 shell 解析？

问个无关的， -l 与 -f 能不能通过环境变量直接传给 fp-multiuuser

**Comment by fatedier** [comment]
shell 脚本中可以支持环境变量，这种方式更加通用，不依赖具体的应用的实现。

**Comment by deadlineOvO** [comment]
> shell 脚本中可以支持环境变量，这种方式更加通用，不依赖具体的应用的实现。

额外一个问题，现在 -l 与 -f 都是只能用一次吗？

**Comment by fatedier** [comment]
没有理解你的问题，shell 脚本是否已经可以解决你目前的问题？如果可以，不再继续讨论这个问题，要求每一个应用去适配自己的运维场景，不是很合理。

**Comment by deadlineOvO** [comment]
> 没有理解你的问题，shell 脚本是否已经可以解决你目前的问题？如果可以，不再继续讨论这个问题，要求每一个应用去适配自己的运维场景，不是很合理。

目前来看应该没问题了吧
