### ISSUE TITLE
Can this be used to *require* user and meta_token?

### ISSUE THREAD

**Issue by mdrichardson** [gofrp/fp-multiuser#5]
I like the idea of this plugin, but have one small issue with it:

If you use this plugin with `token` removed from `frps.ini`, you can still create a tunnel without **any** authentication. Meaning, if you have:

**frps.ini**

```ini
[common]
bind_port = 7000

[plugin.multiuser]
addr = 127.0.0.1:7200
path = /handler
ops = Login
```

and 

**frpc.ini**

```ini
# frpc.ini
[common]
server_addr = x.x.x.x
server_port = 7000

[ssh]
type = tcp
local_port = 22
remote_port = 6000
```

A tunnel is still created, even with the muli-user plugin running.

You can add `token` to `frps.ini`, but then you also have to add it to `frpc.ini` and `user/meta_token` still isn't required.

Ideally, I would like to disallow creation of any tunnels if `frpc.ini` doesn't contain a `user` and `meta_token` that has been specified in `./tokens`

**Comment by fatedier** [comment]
We have fixed this issue in #2 ，i will release a new version for that.
