### ISSUE TITLE
可否增加一个reload功能

### ISSUE THREAD

**Issue by Yang2635** [gofrp/fp-multiuser#9]
使用过程中，会有多设备分配不同 user 和 token 情况，服务端的 `tokens` 文件中可能会动态增添一些鉴权用户与密码，这时需将 fp-multiuser 服务停止并再启动，希望有一个便捷的 reload 选项，对 `tokens` 文件重新加载，而无需重启整个服务

**Comment by yhl452493373** [comment]
试试我改的

https://github.com/yhl452493373/frps-multiuser
